// Copyright 2026 Amandeep Khurana and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newUserPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyShouldGetSubsMetadata bool

	cmd := &cobra.Command{
		Use:         "user",
		Short:       "Fetch the signed-in user profile (live session probe)",
		Long:        "Fetch the signed-in user profile (live session probe)",
		Example:     "  ubereats-pp-cli user",
		Annotations: map[string]string{"pp:endpoint": "user.get", "pp:method": "POST", "pp:path": "/_p/api/getUserV1", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/_p/api/getUserV1"
			params := map[string]string{}
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			bodyMap := map[string]any{}
			var body any = bodyMap
			if cmd.Flags().Changed("should-get-subs-metadata") {
				bodyMap["shouldGetSubsMetadata"] = bodyShouldGetSubsMetadata
			}
			data, _, err := c.PostQueryWithParams(cmd.Context(), path, params, body)

			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			if isDryRunResponse(c.IsDryRun(), data) {
				if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
					return printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "dry-run"}, map[string]bool{"firstName": true, "lastName": true, "email": true})
				}
				return nil
			}
			if !flags.dryRun {
				data = applyResponsePath(data, "data")
			}
			outputData := data
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(outputData, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			formatData := data
			if flags.csv || flags.plain {
				formatData = outputData
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), formatData, flags, map[string]any{"source": "live"}, map[string]bool{"firstName": true, "lastName": true, "email": true})
		},
	}
	cmd.Flags().BoolVar(&bodyShouldGetSubsMetadata, "should-get-subs-metadata", true, "Include Uber One subscription metadata")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
